return {
    PunchesPerExtraShot = 5,
    BFFDamageBonus = 1.5,
    ParasiteDamageMult = 0.5,
    CricketsBodyDamageMult = 0.33,
    BoxOfFriendsPunchesMult = 2,
    SoyMilkPunchesMult = 20,
    ChocolateMilkChargeMult = 0.5,
    BrimstoneChargeMult = 0.16,
    EpicFetusChargeMult = 0.5,
    IpecacChargeMult = 0.2,
    IpecacDamageMod = 0.5,
    MonstrosLungChargeMult = 0.25,
    ProptosisRangeMult = 0.5,
    LudovicoRangeBonus = 100,
    DrFetusChargeMax = 3,
}
