return {
    ChargeLength = 7,
    RangeMult = 10,
    MinimumRange = 80,
    Punches = 5,
    Damage = 0.6,
    DamageLastHit = 2.4,
    Knockback = 5,
    KnockbackLastHitMult = 2.5,
    PunchSize = 2,
    KnockbackBirthrightMult = 5,
    KnockbackBossMult = 0.5,
    LockonWidth = 50,
    ExtraTargetRange = 10,
    ExtraTargetRangeBonus = 5,
    DamageBirthrightFinisher = 1.5,
    DamageBirthrightFinisherB = 0.8,
    SuperCooldown = 10,
    SuperMaxCharge = 80,
    SuperDuration = 0,
    PowerCost = 10,
    RadioBurstFrames = 15,
}
