return {
    ChargeLength = 7,
    RangeMult = 10,
    MinimumRange = 80,
    Punches = 5,
    Damage = 0.6,
    DamageLastHit = 2.4,
    Knockback = 5,
    KnockbackLastHitMult = 2.5,
    PunchSize = 1.5,
    KnockbackBirthrightMult = 5,
    KnockbackBossMult = 0.5,
    LockonWidth = 50,
    ExtraTargetRange = 10,
    ExtraTargetRangeBonus = 5,
    DamageBirthrightFinisher = 1.5,
    DamageBirthrightFinisherB = 0.8,
    SuperCooldown = 10,
    SuperMaxCharge = 80,
    SuperDuration = 0,
    PowerCost = 10,
    -- 20m Emerald Splash phases (kurae → layout → rain)
    -- WAV lengths: ~0.53s / ~1.19s / ~1.75s — scaled to ~5s total at 30 tps.
    RadioKuraeFrames = 18,
    RadioLayoutFrames = 34,
    RadioRainFrames = 65,
    RadioEmeraldsPerFrame = 3,
    RadioRainShakeTimeout = 10,
    RadioSpawnMargin = 80,
    RadioTargetHpFloor = 1,
    RadioTrailCount = 6,
    RadioTrailSpeed = 32,
    -- Weaver waves: first split, then spawn ramps hard toward min interval.
    RadioWeaverInitialCount = 2,
    RadioWeaverIntervalStart = 6,
    RadioWeaverIntervalEnd = 1,
    RadioWeaverSpeedStart = 52,
    RadioWeaverSpeedEnd = 56,
    RadioWeaverMaxAlive = 5,
    RadioWeaverFadeFrames = 6,
    RadioWeaverAlpha = 0.4,
    RadioWeaverNearRadius = 48,
    -- Frames at full opacity, then frames to fade out (independent of kurae phase length).
    RadioTrailHoldFrames = 5,
    RadioTrailFadeFrames = 5,
    -- Edge trails: rain muzzle flashes (layout construction is weaver trails now).
    RadioEdgeTrailMax = 6,
    RadioLayoutEdgeTrailsPerTick = 1,
    RadioLayoutEdgeInterval = 3,
    RadioLayoutEdgeHoldFrames = 8,
    RadioLayoutEdgeFadeFrames = 14,
    RadioLayoutEdgeOscAmplitude = 22,
    RadioLayoutEdgeOscSpeed = 0.8,
    RadioRainEdgeTrailChance = 0.35,
    RadioRainEdgeHoldFrames = 3,
    RadioRainEdgeFadeFrames = 5,
    RadioRainOffscreenChance = 0.12,
    RadioRainSplashAnimChance = 0.28,
    RadioRainInwardNudge = 10,
    -- Procedural net telegraph (counts = max for ~2x2 / L; scaled down in smaller rooms).
    RadioNetPointCount = 12,
    RadioNetChordCount = 3,
    RadioNetPointCountMin = 6,
    RadioNetChordCountMin = 1,
    RadioNetRefPerimeter = 3200,
    RadioNetBorderOutsetX = 28,
    RadioNetBorderOutsetY = 36,
    RadioNetOutsetJitter = 18,
    RadioNetStampAlpha = 0.85,
    RadioNetGhostGrowFrames = 3,
    -- Emerald projectile flight / Emerald Splash scatter
    EmeraldHeight = -30,
    EmeraldFallingAcceleration = 0.01,
    SplashAngleSpread = 11,
    SplashPositionJitter = 9,
    SplashForwardJitter = 6,
}
