# Regenerates scripts/install-mods.ps1 from docs/variant_ids.json
. "$PSScriptRoot\jjba-config.ps1"

$registry = Get-JJBAVariantRegistry
$installPath = Join-Path $JJBA_RepoRoot "scripts\install-mods.ps1"

$lines = @(
    "# Auto-generated by scripts/update-install-mods.ps1",
    "# Creates directory junctions in Isaac mods/ for each JJBA+ mod.",
    '. "$PSScriptRoot\jjba-config.ps1"',
    '$repo = $JJBA_RepoRoot',
    '$mods = Get-JJBAIsaacModsPath',
    ""
)

foreach ($mod in $registry.mods) {
    $display = if ($mod.type -eq "framework") {
        "JJBA+ Framework"
    } else {
        "JJBA+ $($mod.displayName)"
    }
    $lines += "cmd /c mklink /J `"`$mods\$($mod.folder)`" `"`$repo\$($mod.folder)`""
    $lines += "Write-Host `"Linked $display -> $($mod.folder)`""
    $lines += ""
}

$lines += 'Write-Host ""'
$lines += 'Write-Host "JJBA+ mods linked. Enable Framework first, then character mods."'

Set-Content -Path $installPath -Value ($lines -join "`r`n") -Encoding UTF8
Write-Host "Updated $installPath"
